-- First-time PostgreSQL container initialization. Existing data volumes are not modified.
-- The application validates the schema and never runs this script automatically.
CREATE SCHEMA platform;

CREATE TABLE platform.tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR(120) NOT NULL,
    code VARCHAR(48) NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE TABLE platform.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT REFERENCES platform.tenants(id),
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(24) NOT NULL,
    enabled BOOLEAN NOT NULL,
    auth_version BIGINT NOT NULL DEFAULT 0,
    CHECK ((role = 'SUPER_ADMIN' AND tenant_id IS NULL) OR (role = 'TENANT_ADMIN' AND tenant_id IS NOT NULL))
);
CREATE INDEX users_tenant_idx ON platform.users(tenant_id);

CREATE TABLE platform.endpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    extension VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    transport VARCHAR(255) NOT NULL,
    codecs VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    context VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    UNIQUE (tenant_id, extension),
    UNIQUE (tenant_id, id)
);

CREATE TABLE platform.trunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    name VARCHAR(255) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    username VARCHAR(255) NOT NULL,
    transport VARCHAR(255) NOT NULL,
    from_user VARCHAR(255),
    from_domain VARCHAR(255),
    enabled BOOLEAN NOT NULL,
    context VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id)
);

CREATE TABLE platform.queues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    name VARCHAR(255) NOT NULL,
    strategy VARCHAR(255) NOT NULL,
    timeout INTEGER NOT NULL,
    retry INTEGER NOT NULL,
    wrapup_time INTEGER NOT NULL,
    max_length INTEGER NOT NULL,
    music_on_hold VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id)
);

CREATE TABLE platform.ivrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    audio_file VARCHAR(255) NOT NULL,
    timeout INTEGER NOT NULL,
    max_attempts INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL,
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id)
);

CREATE TABLE platform.extensions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    extension_number VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    target_type VARCHAR(255) NOT NULL,
    target_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL,
    context VARCHAR(255) NOT NULL,
    UNIQUE (tenant_id, extension_number),
    UNIQUE (tenant_id, id)
);

CREATE TABLE platform.dialplans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    extension VARCHAR(255) NOT NULL,
    priority INTEGER NOT NULL,
    application VARCHAR(255) NOT NULL,
    application_data VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    context VARCHAR(255) NOT NULL,
    UNIQUE (tenant_id, extension, priority),
    UNIQUE (tenant_id, id)
);

CREATE TABLE platform.queue_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    queue_id BIGINT NOT NULL,
    endpoint_id BIGINT NOT NULL,
    penalty INTEGER NOT NULL CHECK (penalty >= 0),
    paused BOOLEAN NOT NULL,
    UNIQUE (queue_id, endpoint_id),
    FOREIGN KEY (tenant_id, queue_id) REFERENCES platform.queues(tenant_id, id),
    FOREIGN KEY (tenant_id, endpoint_id) REFERENCES platform.endpoints(tenant_id, id)
);
CREATE TABLE platform.ivr_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    ivr_id BIGINT NOT NULL,
    digit VARCHAR(255) NOT NULL,
    action_type VARCHAR(255) NOT NULL,
    target_id BIGINT,
    UNIQUE (ivr_id, digit),
    FOREIGN KEY (tenant_id, ivr_id) REFERENCES platform.ivrs(tenant_id, id),
    CHECK ((action_type = 'HANGUP' AND target_id IS NULL) OR (action_type IN ('QUEUE','EXTENSION','IVR') AND target_id IS NOT NULL))
);
-- Polymorphic target ownership is checked under a tenant row lock by application services.
CREATE INDEX extensions_target_idx ON platform.extensions(target_type, target_id);
CREATE INDEX ivr_options_target_idx ON platform.ivr_options(action_type, target_id);
CREATE INDEX queue_members_endpoint_idx ON platform.queue_members(endpoint_id);
