
-- Incoming calls have their own trunk-scoped namespace, separate from internal dialling.
CREATE TABLE IF NOT EXISTS platform.inbound_routes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
 name VARCHAR(255) NOT NULL,
 trunk_id BIGINT NOT NULL,
 did VARCHAR(255) NOT NULL,
 target_type VARCHAR(255) NOT NULL CHECK (target_type IN ('ENDPOINT','QUEUE','IVR')),
 target_id BIGINT NOT NULL,
 enabled BOOLEAN NOT NULL,
 UNIQUE (tenant_id,trunk_id,did),
 FOREIGN KEY (tenant_id,trunk_id) REFERENCES platform.trunks(tenant_id,id)
);
CREATE INDEX IF NOT EXISTS inbound_routes_target_idx ON platform.inbound_routes(tenant_id,target_type,target_id);
ALTER TABLE platform.ivr_options DROP CONSTRAINT IF EXISTS ivr_options_check;
ALTER TABLE platform.ivr_options DROP CONSTRAINT IF EXISTS ivr_options_action_target_check;
ALTER TABLE platform.ivr_options ADD CONSTRAINT ivr_options_action_target_check CHECK
 ((action_type='HANGUP' AND target_id IS NULL) OR (action_type IN ('ENDPOINT','QUEUE','EXTENSION','IVR') AND target_id IS NOT NULL));
