-- Idempotent initialization for PostgreSQL containers and application startup.
-- Existing tables and data are preserved; only missing schema objects are created.
CREATE SCHEMA IF NOT EXISTS platform;

CREATE TABLE IF NOT EXISTS platform.tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR(120) NOT NULL,
    code VARCHAR(48) NOT NULL UNIQUE CONSTRAINT tenants_number_format CHECK (code ~ '^[0-9]{4,6}$'),
    status VARCHAR(16) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE TABLE IF NOT EXISTS platform.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT REFERENCES platform.tenants(id),
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(24) NOT NULL,
    enabled BOOLEAN NOT NULL,
    auth_version BIGINT NOT NULL DEFAULT 0,
    CHECK ((role = 'SUPER_ADMIN' AND tenant_id IS NULL) OR (role = 'TENANT_ADMIN' AND tenant_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS users_tenant_idx ON platform.users(tenant_id);

CREATE TABLE IF NOT EXISTS platform.endpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    extension VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    transport VARCHAR(255) NOT NULL,
    codecs VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    context VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    UNIQUE (tenant_id, extension),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS platform.trunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    name VARCHAR(255) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    username VARCHAR(255) NOT NULL,
    transport VARCHAR(255) NOT NULL,
    from_user VARCHAR(255),
    from_domain VARCHAR(255),
    enabled BOOLEAN NOT NULL,
    context VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS platform.queues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    name VARCHAR(255) NOT NULL,
    strategy VARCHAR(255) NOT NULL,
    timeout INTEGER NOT NULL,
    retry INTEGER NOT NULL,
    wrapup_time INTEGER NOT NULL,
    max_length INTEGER NOT NULL,
    music_on_hold VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS platform.ivrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    audio_file VARCHAR(255) NOT NULL,
    timeout INTEGER NOT NULL,
    max_attempts INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL,
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS platform.extensions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    extension_number VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    target_type VARCHAR(255) NOT NULL,
    target_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL,
    context VARCHAR(255) NOT NULL,
    UNIQUE (tenant_id, extension_number),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS platform.dialplans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    extension VARCHAR(255) NOT NULL,
    priority INTEGER NOT NULL,
    application VARCHAR(255) NOT NULL,
    application_data VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    context VARCHAR(255) NOT NULL,
    UNIQUE (tenant_id, extension, priority),
    UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS platform.queue_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    queue_id BIGINT NOT NULL,
    endpoint_id BIGINT NOT NULL,
    penalty INTEGER NOT NULL CHECK (penalty >= 0),
    paused BOOLEAN NOT NULL,
    UNIQUE (queue_id, endpoint_id),
    FOREIGN KEY (tenant_id, queue_id) REFERENCES platform.queues(tenant_id, id),
    FOREIGN KEY (tenant_id, endpoint_id) REFERENCES platform.endpoints(tenant_id, id)
);
CREATE TABLE IF NOT EXISTS platform.ivr_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
    ivr_id BIGINT NOT NULL,
    digit VARCHAR(255) NOT NULL,
    action_type VARCHAR(255) NOT NULL,
    target_id BIGINT,
    UNIQUE (ivr_id, digit),
    FOREIGN KEY (tenant_id, ivr_id) REFERENCES platform.ivrs(tenant_id, id),
    CHECK ((action_type = 'HANGUP' AND target_id IS NULL) OR (action_type IN ('ENDPOINT','QUEUE','EXTENSION','IVR') AND target_id IS NOT NULL))
);
-- Polymorphic target ownership is checked under a tenant row lock by application services.
CREATE INDEX IF NOT EXISTS extensions_target_idx ON platform.extensions(target_type, target_id);
CREATE INDEX IF NOT EXISTS ivr_options_target_idx ON platform.ivr_options(action_type, target_id);
CREATE INDEX IF NOT EXISTS queue_members_endpoint_idx ON platform.queue_members(endpoint_id);

-- Minimal realtime tables used by the backend. Existing Asterisk tables are preserved.
-- Additional PBX features may require the migrations from the installed Asterisk release.
CREATE TABLE IF NOT EXISTS public.ps_aors (
    id VARCHAR(255) PRIMARY KEY, contact VARCHAR(255), max_contacts INTEGER,
    remove_existing VARCHAR(10), qualify_frequency INTEGER
);
CREATE TABLE IF NOT EXISTS public.ps_auths (
    id VARCHAR(255) PRIMARY KEY, auth_type VARCHAR(40), username VARCHAR(40), password VARCHAR(80)
);
CREATE TABLE IF NOT EXISTS public.ps_endpoints (
    id VARCHAR(255) PRIMARY KEY, transport VARCHAR(40), aors VARCHAR(2048), auth VARCHAR(255),
    outbound_auth VARCHAR(255), context VARCHAR(40), disallow VARCHAR(200), allow VARCHAR(200),
    direct_media VARCHAR(10), force_rport VARCHAR(10), rewrite_contact VARCHAR(10),
    rtp_symmetric VARCHAR(10), from_user VARCHAR(40), from_domain VARCHAR(40),
    callerid VARCHAR(40), set_var VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS public.ps_endpoint_id_ips (
    id VARCHAR(255) PRIMARY KEY, endpoint VARCHAR(255), match VARCHAR(80)
);
CREATE TABLE IF NOT EXISTS public.queues (
    name VARCHAR(128) PRIMARY KEY, musiconhold VARCHAR(128), context VARCHAR(128), timeout INTEGER,
    ringinuse VARCHAR(10), monitor_format VARCHAR(8), announce_frequency INTEGER,
    announce_position VARCHAR(128), periodic_announce_frequency INTEGER, retry INTEGER,
    wrapuptime INTEGER, autofill VARCHAR(10), maxlen INTEGER, strategy VARCHAR(40),
    joinempty VARCHAR(128), leavewhenempty VARCHAR(128)
);
CREATE TABLE IF NOT EXISTS public.queue_members (
    queue_name VARCHAR(80) NOT NULL, interface VARCHAR(80) NOT NULL, membername VARCHAR(80),
    state_interface VARCHAR(80), penalty INTEGER, paused INTEGER, uniqueid INTEGER NOT NULL UNIQUE,
    wrapuptime INTEGER, ringinuse VARCHAR(10), PRIMARY KEY (queue_name, interface)
);
CREATE TABLE IF NOT EXISTS extensions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    context VARCHAR(40) NOT NULL,
    exten VARCHAR(40) NOT NULL,
    priority INTEGER NOT NULL,
    app VARCHAR(40) NOT NULL,
    appdata VARCHAR(256) NOT NULL,
    UNIQUE (context, exten, priority)
);

-- CDR storage is initialized together with the other platform tables.
CREATE TABLE IF NOT EXISTS platform.cdr (
    id VARCHAR(64) PRIMARY KEY,
    tenant_id BIGINT REFERENCES platform.tenants(id),
    cdr_sequence INTEGER NOT NULL CHECK (cdr_sequence >= 0),
    unique_id VARCHAR(150) NOT NULL,
    linked_id VARCHAR(150),
    src VARCHAR(255) NOT NULL,
    dst VARCHAR(255) NOT NULL,
    src_name VARCHAR(255),
    dst_name VARCHAR(255),
    context VARCHAR(255),
    channel VARCHAR(255),
    dst_channel VARCHAR(255),
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    answer_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    duration INTEGER NOT NULL CHECK (duration >= 0),
    billsec INTEGER NOT NULL CHECK (billsec >= 0 AND billsec <= duration),
    disposition VARCHAR(32) NOT NULL,
    recording_path VARCHAR(1000),
    UNIQUE (tenant_id, unique_id, cdr_sequence),
    CHECK (end_time >= start_time)
);
CREATE INDEX IF NOT EXISTS cdr_tenant_start_idx ON platform.cdr (tenant_id, start_time DESC, id);
CREATE INDEX IF NOT EXISTS cdr_start_idx ON platform.cdr (start_time DESC, id);
CREATE INDEX IF NOT EXISTS cdr_tenant_src_idx ON platform.cdr (tenant_id, src);
CREATE INDEX IF NOT EXISTS cdr_tenant_dst_idx ON platform.cdr (tenant_id, dst);
CREATE INDEX IF NOT EXISTS cdr_linked_idx ON platform.cdr (tenant_id, linked_id);

-- Incoming calls have their own trunk-scoped namespace, separate from internal dialling.
CREATE TABLE IF NOT EXISTS platform.inbound_routes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 tenant_id BIGINT NOT NULL REFERENCES platform.tenants(id),
 name VARCHAR(255) NOT NULL,
 trunk_id BIGINT NOT NULL,
 did VARCHAR(255) NOT NULL,
 target_type VARCHAR(255) NOT NULL CHECK (target_type IN ('ENDPOINT','QUEUE','IVR')),
 target_id BIGINT NOT NULL,
 enabled BOOLEAN NOT NULL,
 UNIQUE (tenant_id,trunk_id,did),
 FOREIGN KEY (tenant_id,trunk_id) REFERENCES platform.trunks(tenant_id,id)
);
CREATE INDEX IF NOT EXISTS inbound_routes_target_idx ON platform.inbound_routes(tenant_id,target_type,target_id);
ALTER TABLE platform.ivr_options DROP CONSTRAINT IF EXISTS ivr_options_check;
ALTER TABLE platform.ivr_options DROP CONSTRAINT IF EXISTS ivr_options_action_target_check;
ALTER TABLE platform.ivr_options ADD CONSTRAINT ivr_options_action_target_check CHECK
 ((action_type='HANGUP' AND target_id IS NULL) OR (action_type IN ('ENDPOINT','QUEUE','EXTENSION','IVR') AND target_id IS NOT NULL));
